# turret_presets.py
# Preset profiles for turret tracking & YOLO detection behavior
#
# === TRACKING SETTINGS DOCUMENTATION ===
#
# GENERAL SETTINGS (applicable to all detection modes):
#   tracking_speed (1-100): Multiplier on servo movement speed. Higher = faster response.
#   movement_sensitivity (1-100): Base gain multiplier for error-to-movement conversion.
#   smoothing_factor (0.0-1.0): IIR filter blend. Lower = snappier, Higher = smoother.
#   deadzone (0-200 px): No-movement zone around frame center.
#   snap_threshold (0-400 px): Distance for instant snap vs gradual approach.
#
# NEW AIMING SETTINGS (added Dec 2024):
#   aim_aggression (0-100): Controls how aggressively the turret pursues center.
#       0 = conservative/lazy, 100 = maximum aggression with boosted final approach.
#   final_approach_boost (True/False): When True, applies 2-3x speed multiplier
#       and reduces smoothing when target is within 2x deadzone radius.
#
# YOLO-SPECIFIC SETTINGS (only for YOLO detection modes):
#   yolo_confidence (0.0-1.0): Minimum confidence threshold for detections.
#   yolo_classes (string): Comma-separated YOLO class names to detect.
#   yolo_model (string): YOLO model file to use (yolov8n/s/m/l/x.pt).
#
# DETECTION MODE:
#   detection_mode: If present, the preset will switch the detection mode dropdown.
#       (Most size-tier presets include it to ensure consistent behavior.)
#
# MOTION DETECTION SETTINGS (for BackgroundSub/FrameDiff modes):
#   threshold, blur_kernel, min_contour, max_contour, dilate_iter, backsub_warmup
#

# Precision Aim defaults (persisted + presettable). These are conservative for 1280x720.
PRECISION_DEFAULTS = {
    "precision_mode": False,
    "precision_roi": 48,
    "precision_kp": 0.02,
    "precision_ki": 0.001,
    "precision_kd": 0.005,
    "precision_hfov": 90.0,
    "precision_max_step": 1.0,
    "precision_frac_threshold": 0.25,
}

PRESETS = {
    # ======================================================================
    # CONSISTENT PRESET NAMING (Dec 2025)
    # Format: "Target / <Detection Mode> / <Size Tier> / <Profile>"
    # Size tiers:
    #   Small  = rat-sized contour band
    #   Medium = dog-sized contour band
    #   Person = person/human-sized contour band
    #
    # Goal: while you learn the technical UI settings, these presets give you
    # predictable, size-gated behavior that prevents giant blobs from locking
    # and firing. All presets set BOTH min_contour and max_contour.
    # ======================================================================

    # ----------------------------------------------------------------------
    # Shared tracking behavior (applies across modes)
    # ----------------------------------------------------------------------

    "Behavior / Smooth": {
        "tracking_speed": 45,
        "movement_sensitivity": 35,
        "smoothing_factor": 0.75,
        "deadzone": 22,
        "snap_threshold": 90,
        "aim_aggression": 35,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Behavior / Responsive": {
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.55,
        "deadzone": 18,
        "snap_threshold": 120,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Behavior / Aggressive": {
        "tracking_speed": 80,
        "movement_sensitivity": 65,
        "smoothing_factor": 0.35,
        "deadzone": 14,
        "snap_threshold": 160,
        "aim_aggression": 75,
        "final_approach_boost": True,
        # Single-strike aiming: one decisive move then short hold (avoids many micro-steps)
        "auto_strike_enabled": True,
        "auto_strike_hold_ms": 320,
        "auto_strike_cooldown_ms": 260,
        "auto_strike_min_error_deg": 2.0,
        **PRECISION_DEFAULTS,
    },

    # ----------------------------------------------------------------------
    # Target / Frame Difference (Mode 0)
    # ----------------------------------------------------------------------

    "Target / Frame Difference / Small / Balanced": {
        "detection_mode": "Frame Difference",
        "threshold": 30,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 900,
        "max_contour": 25000,
        "backsub_warmup": 10,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Frame Difference / Small / Sensitive": {
        "detection_mode": "Frame Difference",
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 2,
        "min_contour": 500,
        "max_contour": 22000,
        "backsub_warmup": 10,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 22,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Frame Difference / Medium / Balanced": {
        "detection_mode": "Frame Difference",
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 10,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Frame Difference / Medium / Sensitive": {
        "detection_mode": "Frame Difference",
        "threshold": 24,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 6000,
        "max_contour": 160000,
        "backsub_warmup": 10,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 20,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Frame Difference / Person / Precision Clamp": {
        "detection_mode": "Frame Difference",
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 1,
        "min_contour": 60000,
        "max_contour": 450000,
        "backsub_warmup": 10,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        # Enable precision for large targets (helps final lock without overshoot)
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },

    # ----------------------------------------------------------------------
    # Target / Background Subtraction (Mode 1)
    # ----------------------------------------------------------------------

    "Target / Background Subtraction / Small / Stable": {
        "detection_mode": "Background Subtraction",
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 900,
        "max_contour": 25000,
        "backsub_warmup": 25,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Background Subtraction / Small / Sensitive": {
        "detection_mode": "Background Subtraction",
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 2,
        "min_contour": 500,
        "max_contour": 22000,
        "backsub_warmup": 18,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 22,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Background Subtraction / Medium / Balanced": {
        "detection_mode": "Background Subtraction",
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 30,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Background Subtraction / Medium / Stable": {
        "detection_mode": "Background Subtraction",
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 40,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.55,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Background Subtraction / Person / Precision Clamp": {
        "detection_mode": "Background Subtraction",
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 1,
        "min_contour": 60000,
        "max_contour": 450000,
        "backsub_warmup": 35,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },

    # ----------------------------------------------------------------------
    # Target / Hybrid: Frame Diff + BackSub (Mode 3)
    # ----------------------------------------------------------------------

    "Target / Hybrid: Frame Diff + BackSub / Small / OR Lenient": {
        "detection_mode": "Hybrid: Frame Diff + BackSub",
        "fusion_strategy": 1,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 900,
        "max_contour": 25000,
        "backsub_warmup": 20,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + BackSub / Small / AND Strict": {
        "detection_mode": "Hybrid: Frame Diff + BackSub",
        "fusion_strategy": 0,
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 1200,
        "max_contour": 25000,
        "backsub_warmup": 25,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.60,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + BackSub / Medium / AND Strict": {
        "detection_mode": "Hybrid: Frame Diff + BackSub",
        "fusion_strategy": 0,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 25,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + BackSub / Medium / OR Lenient": {
        "detection_mode": "Hybrid: Frame Diff + BackSub",
        "fusion_strategy": 1,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 20,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + BackSub / Person / Precision Clamp": {
        "detection_mode": "Hybrid: Frame Diff + BackSub",
        "fusion_strategy": 0,
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 1,
        "min_contour": 60000,
        "max_contour": 450000,
        "backsub_warmup": 30,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },

    # ----------------------------------------------------------------------
    # Target / YOLO (Mode 2)
    # ----------------------------------------------------------------------

    "Target / YOLO / Small / Sensitive": {
        "detection_mode": "YOLO Object Detection",
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.35,
        "yolo_min_area": 5000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / YOLO / Small / Balanced": {
        "detection_mode": "YOLO Object Detection",
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 7000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / YOLO / Medium / Balanced": {
        "detection_mode": "YOLO Object Detection",
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.45,
        "yolo_min_area": 15000,
        "yolo_max_results": 5,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / YOLO / Medium / Sensitive": {
        "detection_mode": "YOLO Object Detection",
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 12000,
        "yolo_max_results": 5,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 20,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / YOLO / Person / Precision": {
        "detection_mode": "YOLO Object Detection",
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.50,
        "yolo_min_area": 40000,
        "yolo_max_results": 5,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },

    # ----------------------------------------------------------------------
    # Target / Hybrid: Frame Diff + YOLO (Mode 4)
    # ----------------------------------------------------------------------

    "Target / Hybrid: Frame Diff + YOLO / Small / Motion Gate Lenient": {
        "detection_mode": "Hybrid: Frame Diff + YOLO",
        "motion_gate_threshold": 0.85,
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 900,
        "max_contour": 25000,
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.35,
        "yolo_min_area": 5000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + YOLO / Small / Motion Gate Balanced": {
        "detection_mode": "Hybrid: Frame Diff + YOLO",
        "motion_gate_threshold": 0.95,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 900,
        "max_contour": 25000,
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 7000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + YOLO / Medium / Motion Gate Balanced": {
        "detection_mode": "Hybrid: Frame Diff + YOLO",
        "motion_gate_threshold": 1.0,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 140000,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.45,
        "yolo_min_area": 15000,
        "yolo_max_results": 5,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + YOLO / Medium / Motion Gate Lenient": {
        "detection_mode": "Hybrid: Frame Diff + YOLO",
        "motion_gate_threshold": 0.9,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 2,
        "min_contour": 8000,
        "max_contour": 160000,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 12000,
        "yolo_max_results": 5,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: Frame Diff + YOLO / Person / Motion Gate Strict": {
        "detection_mode": "Hybrid: Frame Diff + YOLO",
        "motion_gate_threshold": 1.15,
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 1,
        "min_contour": 60000,
        "max_contour": 450000,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.50,
        "yolo_min_area": 40000,
        "yolo_max_results": 5,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },

    # ----------------------------------------------------------------------
    # Target / Hybrid: BackSub + YOLO (Best) (Mode 5)
    # ----------------------------------------------------------------------

    "Target / Hybrid: BackSub + YOLO (Best) / Small / Overlap Lenient": {
        "detection_mode": "Hybrid: BackSub + YOLO (Best)",
        "overlap_threshold": 22.0,
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 900,
        "max_contour": 25000,
        "backsub_warmup": 25,
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.35,
        "yolo_min_area": 5000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: BackSub + YOLO (Best) / Small / Overlap Balanced": {
        "detection_mode": "Hybrid: BackSub + YOLO (Best)",
        "overlap_threshold": 26.0,
        "threshold": 28,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 900,
        "max_contour": 25000,
        "backsub_warmup": 30,
        "yolo_classes": "person",
        "yolo_model": "yolov8s.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 7000,
        "yolo_max_results": 5,
        "tracking_speed": 60,
        "movement_sensitivity": 45,
        "smoothing_factor": 0.55,
        "deadzone": 22,
        "snap_threshold": 120,
        "aim_aggression": 50,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: BackSub + YOLO (Best) / Medium / Overlap Balanced": {
        "detection_mode": "Hybrid: BackSub + YOLO (Best)",
        "overlap_threshold": 28.0,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 140000,
        "backsub_warmup": 30,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.45,
        "yolo_min_area": 15000,
        "yolo_max_results": 5,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: BackSub + YOLO (Best) / Medium / Overlap Lenient": {
        "detection_mode": "Hybrid: BackSub + YOLO (Best)",
        "overlap_threshold": 24.0,
        "threshold": 26,
        "blur_kernel": 5,
        "dilate_iter": 1,
        "min_contour": 8000,
        "max_contour": 160000,
        "backsub_warmup": 35,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.40,
        "yolo_min_area": 12000,
        "yolo_max_results": 5,
        "tracking_speed": 65,
        "movement_sensitivity": 50,
        "smoothing_factor": 0.50,
        "deadzone": 20,
        "snap_threshold": 130,
        "aim_aggression": 55,
        "final_approach_boost": True,
        **PRECISION_DEFAULTS,
    },

    "Target / Hybrid: BackSub + YOLO (Best) / Person / Overlap Strict": {
        "detection_mode": "Hybrid: BackSub + YOLO (Best)",
        "overlap_threshold": 32.0,
        "threshold": 24,
        "blur_kernel": 3,
        "dilate_iter": 1,
        "min_contour": 60000,
        "max_contour": 450000,
        "backsub_warmup": 35,
        "yolo_classes": "person",
        "yolo_model": "yolov8m.pt",
        "yolo_confidence": 0.50,
        "yolo_min_area": 40000,
        "yolo_max_results": 5,
        "tracking_speed": 70,
        "movement_sensitivity": 55,
        "smoothing_factor": 0.45,
        "deadzone": 16,
        "snap_threshold": 150,
        "aim_aggression": 60,
        "final_approach_boost": True,
        "precision_mode": True,
        "precision_roi": 64,
        "precision_kp": 0.018,
        "precision_ki": 0.001,
        "precision_kd": 0.006,
        "precision_hfov": 90.0,
        "precision_max_step": 0.9,
        "precision_frac_threshold": 0.25,
    },
}
