"""Smart Sentry v2 tooltip definitions.

Keep tooltip copy separate from the UI builder so descriptions stay consistent,
reviewable, and easy to expand as Smart Sentry evolves.
"""

from __future__ import annotations


SENTRY_V2_TOOLTIPS: dict[str, str] = {
    "enable_sentry": "Master enable for Smart Sentry. ON lets the engine scan, track, and engage using its current rules. OFF keeps the module paused and prevents automatic action.",
    "camera_source": "Camera source for Smart Sentry. Leave blank to use the main app feed. Enter a camera index like 1 or a stream/URL path to open a separate source here. Blank avoids camera ownership conflicts.",
    "camera_width": "Requested secondary camera width. Range: 160 to 3840 pixels. Higher values increase detail but also CPU/GPU load and USB bandwidth use. Lower values reduce load and usually improve stability.",
    "camera_height": "Requested secondary camera height. Range: 120 to 2160 pixels. Higher values give more detail but cost more processing power. Lower values reduce load and can improve frame reliability.",
    "camera_toggle": "Open or close Smart Sentry's own secondary camera. Use this only when you want Smart Sentry to run from a separate camera instead of the main app feed.",
    "connection_mode": "Hardware connection topology for Smart Sentry. Choose the wiring mode that matches your setup. Modes using more direct USB links reduce dependency on WiFi. More wireless modes reduce cabling but depend more on network stability.",
    "esp32_port": "ESP32 serial COM port. Example: COM20. This is the USB serial link used for ASCII IO/control in USB modes.",
    "scan_esp32_ports": "Scan Windows serial ports and list candidates for the ESP32 USB connection. Use this when the COM port changes or after reconnecting hardware.",
    "esp32_port_list": "Detected ESP32-side COM ports from the latest scan. Selecting an entry copies that port into the ESP32 COM field.",
    "esp32_baud": "ESP32 serial baud rate. Range: 9600 to 921600. Higher values reduce command latency if the firmware supports them. Lower values are slower but may be more tolerant on unstable links.",
    "debug_port": "Debug Board serial COM port. Example: COM19. This is the USB link used for bus-servo pan/tilt control when a debug board is part of the setup.",
    "scan_debug_ports": "Scan Windows serial ports and list candidates for the Debug Board USB connection. Use this after reconnecting the board or if Windows changed the COM number.",
    "debug_port_list": "Detected Debug Board COM ports from the latest scan. Selecting an entry copies that port into the Debug Board COM field.",
    "debug_baud": "Debug Board serial baud rate. Range: 9600 to 921600. Higher values can improve response time if supported. Lower values are slower but may be easier to keep stable on noisy links.",
    "pan_servo_id": "Bus-servo ID for the pan axis. Range: 0 to 253. Changing this must match the servo's programmed ID or Smart Sentry will move the wrong servo or none at all.",
    "tilt_servo_id": "Bus-servo ID for the tilt axis. Range: 0 to 253. Changing this must match the tilt servo's programmed ID.",
    "servo_move_time": "Requested bus-servo move time per command. Range: 0 to 1000 ms. Higher values make movement smoother and slower. Lower values make movement faster and more abrupt.",
    "preset_servo_smooth": "Smooth move-time preset. Uses a higher bus-servo move time so turret motion is slower, calmer, and easier to observe. Best for careful tuning and indoor precision tests.",
    "preset_servo_balanced": "Balanced move-time preset. Keeps bus-servo timing in the middle so the turret is responsive without becoming overly abrupt. This is the default reference timing.",
    "preset_servo_fast": "Fast move-time preset. Uses a lower bus-servo move time so the turret snaps harder and reacts faster, but overshoot risk is higher if the rest of the tuning is aggressive.",
    "udp_host": "ESP32 WiFi host or IP address for UDP control. Example: 192.168.4.1. This is used in the WiFi connection modes.",
    "udp_port": "UDP port used for ESP32 WiFi control. Range: 1 to 65535. This must match the port configured in ESP32 firmware.",
    "invert_pan": "Reverse the pan direction. Enable this if moving right in software makes the turret move left in real hardware.",
    "invert_tilt": "Reverse the tilt direction. Enable this if moving up in software makes the turret move down in real hardware.",
    "connect_toggle": "Open or close the currently configured communication links. When settings are correct, Connect establishes the serial and/or WiFi links required by the chosen connection mode.",
    "detection_mode": "Detection algorithm used to find targets. For a simple moving-object workflow, use Motion-Locked Filtered Target so motion is mandatory and size, color, and class only refine moving objects.",
    "preset_detection_frame_diff": "Frame Difference preset. Uses simple frame-to-frame motion detection with tighter contour limits to make moving blobs stand out. Good for testing raw motion response without background learning or AI classification.",
    "preset_detection_backsub": "Background Subtraction preset. Learns a background model and highlights foreground changes. This makes it steadier than frame difference when the camera is stable, but slower to adapt when the scene changes heavily.",
    "preset_detection_yolo": "YOLO Precision preset. Uses only YOLO object detection with higher confidence and area thresholds so the behavior is clearly object-ID driven rather than motion driven.",
    "preset_detection_dual_motion": "Dual Motion preset. Combines frame difference and background subtraction so motion must survive two simple detectors. This is stricter than either motion mode alone.",
    "preset_detection_motion_yolo": "Motion-Gated YOLO preset. Uses motion to decide when YOLO should matter, making it visibly more selective than full-time YOLO modes.",
    "preset_detection_best_hybrid": "Best Hybrid YOLO preset. Background subtraction feeds a more permissive YOLO stage, making this a balanced hybrid that still prefers likely object detections.",
    "preset_detection_color": "Color Watch preset. Uses pure color detection with a red default so the effect is obvious during testing. Change the color preset afterward if your target is not red.",
    "preset_detection_color_motion": "Color plus Motion preset. Requires both the red color mask and frame-difference motion, so behavior is narrower and more obvious than pure color or pure motion alone.",
    "preset_detection_color_backsub": "Color plus Background preset. Uses red color masking with background subtraction, favoring colored foreground objects over raw motion alone.",
    "preset_detection_color_yolo": "Color plus YOLO preset. Uses red color filtering together with YOLO so the system favors colored objects that also look like known classes.",
    "preset_detection_motion_locked": "Motion-Locked Filtered preset. Motion is mandatory and color or YOLO only refine the moving object. This is the most sentry-specific mode for stable single-target tracking.",
    "min_contour_area": "Minimum contour area in pixels. Range: 0 to 5,000,000 px. Increase it to ignore small noise and flicker. Decrease it to detect smaller motion blobs.",
    "max_contour_area": "Maximum contour area in pixels. Range: 0 to 5,000,000 px. Increase it to allow larger moving shapes. Decrease it to reject oversized blobs such as whole-scene changes.",
    "yolo_model": "YOLO model file used for object detection. Smaller models are usually faster with lower accuracy. Larger models are usually slower with better recognition quality.",
    "load_yolo_model": "Load the currently selected YOLO model into memory. Use this after changing the model selection.",
    "yolo_classes": "Comma-separated YOLO class names Smart Sentry should pay attention to. Example: person,car,dog. Adding more classes increases what can be detected. Narrowing the list reduces distractions.",
    "yolo_confidence": "Minimum YOLO confidence score. Range: 0.05 to 1.00. Increase it to keep only more certain detections. Decrease it to detect weaker or smaller targets, with more false positives.",
    "yolo_min_area": "Minimum YOLO box area in pixels. Range: 0 to 10,000,000 px. Increase it to ignore tiny distant detections. Decrease it to allow smaller targets.",
    "color_preset": "HSV color preset used to refine moving-object detection. Choose Any to ignore color. Choose a preset to keep only moving targets that match that color.",
    "color_min_area": "Minimum color-blob area in pixels. Range: 1 to 5,000,000 px. Increase it to ignore small color noise. Decrease it to detect smaller colored targets.",
    "color_max_area": "Maximum color-blob area in pixels. Range: 1 to 5,000,000 px. Increase it to allow larger colored regions. Decrease it to reject oversized colored areas such as backgrounds.",
    "fusion_strategy": "How color and another detector are combined in hybrid color modes. AND is stricter and reduces false positives. OR is looser and finds more candidates.",
    "fusion_overlap": "Required overlap between detectors in percent. Range: 0 to 100%. Increase it to demand stronger agreement between detectors. Decrease it to allow looser matching.",
    "motion_gate_threshold": "Motion gate threshold used before YOLO in hybrid motion+YOLO modes. Range: 0.1 to 50.0%. Increase it to require stronger motion before YOLO runs. Decrease it to allow more frames through the gate.",
    "allowed_classes": "List of classes allowed to validate a moving target. Leave the list empty to accept any moving object. Select one or more classes to require a moving object to match those YOLO classes.",
    "preset_filter_wide_net": "Wide Net preset. Accepts any class with lower confidence and very small targets allowed. Use it when you want the sentry to react to as much as possible.",
    "preset_filter_human_focus": "Human Focus preset. Restricts tracking to people and uses stricter confidence and size limits so non-human detections are filtered out more aggressively.",
    "preset_filter_vehicle_watch": "Vehicle Watch preset. Focuses on vehicle-related classes and ignores smaller detections more strongly. Use it when you want large moving machines to dominate.",
    "preset_filter_small_movers": "Small Movers preset. Keeps smaller targets in play with permissive confidence and a low minimum size, useful when testing pets, small motion, or distant targets.",
    "preset_filter_large_close": "Large Close preset. Requires larger, more confident targets so only obvious near or dominant detections survive the filter.",
    "select_all_classes": "Select every YOLO class in the allowed list. This is the widest possible target filter.",
    "select_no_classes": "Clear the allowed class list. With no classes selected, YOLO-qualified targets will normally be filtered out.",
    "min_confidence": "Minimum confidence after class filtering. Range: 0.10 to 0.99. Increase it to accept only stronger detections. Decrease it to keep weaker detections.",
    "min_size": "Minimum target size as a percent of the frame. Range: 0.00 to 50.00%. Increase it to ignore smaller targets. Decrease it to allow smaller targets.",
    "max_size": "Maximum target size as a percent of the frame. Range: 0.00 to 100.00%, where 0 disables the limit. Increase it to allow larger targets. Decrease it to reject very large close-range boxes.",
    "weight_proximity": "Threat weight for closeness to image center. Range: 0.00 to 1.00. Higher values make center-biased targets rank higher. Lower values reduce the importance of center position.",
    "weight_size": "Threat weight for target size. Range: 0.00 to 1.00. Higher values prioritize larger targets. Lower values reduce size influence.",
    "weight_confidence": "Threat weight for detector confidence. Range: 0.00 to 1.00. Higher values favor more certain detections. Lower values make certainty matter less.",
    "weight_class_priority": "Threat weight for configured class priority. Range: 0.00 to 1.00. Higher values make preferred classes dominate ranking more strongly.",
    "weight_speed": "Threat weight for movement speed. Range: 0.00 to 1.00. Higher values prioritize faster-moving targets. Lower values reduce motion urgency.",
    "weight_persistence": "Threat weight for time spent in frame. Range: 0.00 to 1.00. Higher values favor persistent targets. Lower values make dwell time matter less.",
    "weight_approach": "Threat weight for movement toward center/guard focus. Range: 0.00 to 1.00. Higher values prioritize approaching targets. Lower values reduce approach bias.",
    "ml_refinement": "Enable optional machine-learning refinement on top of the hand-tuned threat score. Use only when the required model and sklearn dependency are available.",
    "preset_threat_balanced_guard": "Balanced Guard preset. Keeps center position, preferred class, and basic motion all relevant without letting any single factor dominate. Use this as the neutral reference profile when comparing the other Threat AI presets.",
    "preset_threat_crosshair_snap": "Crosshair Snap preset. Strongly favors targets already near the camera center and moving into the crosshair. This makes Smart Sentry stick to center-biased candidates much more aggressively than the other Threat AI profiles.",
    "preset_threat_speed_hunter": "Speed Hunter preset. Gives much more weight to motion speed and persistence, so fast-moving targets rise above slower objects even if they are not yet centered.",
    "preset_threat_big_target_bias": "Big Target Bias preset. Prioritizes larger detections and more confident boxes. Use this when you want obvious close or large targets to beat smaller moving ones.",
    "preset_threat_class_first": "Class First preset. Makes configured class priority and detector confidence dominate ranking much more strongly than speed, size, or proximity. This is useful when allowed classes matter more than raw motion.",
    "auto_trigger": "Allow Smart Sentry to fire automatically when engagement conditions are met. OFF keeps aiming and tracking active but requires manual fire.",
    "trigger_mode": "Trigger hardware type. Water/MOSFET is for direct IO switching. Projectile/BB Servo is for servo-actuated firing hardware. Choose the mode that matches the real firing mechanism.",
    "preset_engage_demo_track": "Demo Track Only preset. Never fires automatically. It moves slowly, settles longer, and uses tight aim-lock rules so centering behavior is easy to watch on screen.",
    "preset_engage_indoor_precision": "Indoor Precision preset. Conservative and exact. It engages only stronger threats, uses slower servo speed, smaller correction steps, and stricter lock tolerances for close indoor testing.",
    "preset_engage_balanced_response": "Balanced Response preset. Default middle-ground profile. It auto-engages at a moderate speed with controlled burst size and moderate lock requirements.",
    "preset_engage_outdoor_chase": "Outdoor Chase preset. Faster and less strict. It reacts sooner, tolerates more aim error, and uses larger correction steps to stay responsive against moving targets over a wider scene.",
    "preset_engage_saturation_burst": "Saturation Burst preset. Most aggressive firing profile. It uses short cooldowns and longer bursts so the behavioral difference is obvious, but it is also the least restrained option.",
    "preset_master_demo_observer": "Demo Observer master profile. Applies a calm full-stack setup for visibly slow tracking: Motion-Locked Filtered detection, Wide Net filtering, Crosshair Snap threat ranking, Demo Track Only engagement, and Smooth bus-servo timing.",
    "preset_master_indoor_precision": "Indoor Precision master profile. Applies a cautious and exact stack for controlled indoor work: YOLO Precision detection, Human Focus filtering, Class First threat ranking, Indoor Precision engagement, and Smooth bus-servo timing.",
    "preset_master_balanced_sentry": "Balanced Sentry master profile. Applies a general-purpose stack for normal sentry operation: Motion-Locked Filtered detection, Wide Net filtering, Balanced Guard threat ranking, Balanced Response engagement, and Balanced bus-servo timing.",
    "preset_master_vehicle_intercept": "Vehicle Intercept master profile. Applies a faster stack for larger moving machines: Motion-Gated YOLO detection, Vehicle Watch filtering, Speed Hunter threat ranking, Outdoor Chase engagement, and Balanced-to-fast bus-servo timing.",
    "preset_master_aggressive_pursuit": "Aggressive Pursuit master profile. Applies the most forceful coordinated stack: Best Hybrid YOLO detection, Wide Net filtering, Speed Hunter threat ranking, Saturation Burst engagement, and Fast bus-servo timing.",
    "min_threat": "Minimum threat score required before Smart Sentry can engage a target. Range: 0.05 to 0.95. Increase it to be more selective. Decrease it to engage more readily.",
    "burst_shots": "Number of shots in each burst. Range: 1 to 10. Higher values fire longer bursts. Lower values reduce ammo or water use.",
    "burst_interval": "Delay between burst shots in milliseconds. Range: 20 to 500 ms. Higher values slow the burst. Lower values make bursts faster and more aggressive.",
    "inter_target_cooldown": "Cooldown after engaging one target before moving to the next. Range: 0.1 to 5.0 s. Higher values make the system calmer and less jumpy. Lower values speed up retargeting.",
    "cycle_cooldown": "Cooldown after a full engagement cycle. Range: 0.5 to 30.0 s. Higher values slow repeated engagement loops. Lower values keep the system more active.",
    "max_targets_per_cycle": "Maximum number of targets processed in one cycle. Range: 1 to 10. Higher values allow more engagements before resetting. Lower values keep each cycle shorter.",
    "optimize_travel": "Reorder engagements to reduce servo travel between targets. ON usually improves overall efficiency. OFF keeps a simpler queue order.",
    "engagement_speed": "Servo speed used during engagement. Range: 10 to 100. Higher values make snap-aim faster and more aggressive. Lower values make tracking smoother but slower.",
    "precision_enable": "Enable a precision refinement phase for small or distant targets before firing. ON improves fine aim but can add delay. OFF keeps engagement faster but less precise.",
    "precision_settle": "Time allowed for precision refinement before firing. Range: 0.1 to 3.0 s. Higher values allow more correction time. Lower values fire sooner.",
    "precision_step": "Maximum correction step per precision update in degrees. Range: 0.1 to 5.0 deg. Higher values correct faster but can overshoot. Lower values are smoother but slower.",
    "guard_mode": "Idle/guard behavior when no target is engaged. Static holds one position. Sweep scans left to right. Waypoint follows saved points. Random scans within configured limits.",
    "guard_pan": "Pan angle used as the base guard position. Range: 5 to 185 deg. Higher values look farther right. Lower values look farther left.",
    "guard_tilt": "Tilt angle used as the base guard position. Range: 10 to 130 deg. Higher values look farther down or up depending on hardware orientation. Lower values move the opposite way.",
    "pan_limit_min": "Minimum allowed pan angle. Lower values expand left travel. Higher values restrict left travel and keep the turret inside safer mechanical limits.",
    "pan_limit_max": "Maximum allowed pan angle. Higher values expand right travel. Lower values restrict right travel and protect the mechanism.",
    "tilt_limit_min": "Minimum allowed tilt angle. Lower values allow more travel toward the lower bound. Higher values restrict that direction to avoid collisions or stall zones.",
    "tilt_limit_max": "Maximum allowed tilt angle. Higher values allow more travel toward the upper bound. Lower values reduce vertical reach and can protect hardware.",
    "go_guard": "Command the turret to move immediately to the configured guard position.",
    "set_current_guard": "Use the turret's current position as the new guard position. Helpful after manually aiming to the exact resting angle you want.",
    "sweep_min": "Minimum pan limit for sweep mode. Range: 5 to 185 deg. Increasing it shifts the sweep window right. Decreasing it shifts the left edge farther left.",
    "sweep_max": "Maximum pan limit for sweep mode. Range: 5 to 185 deg. Increasing it extends the sweep farther right. Decreasing it narrows the sweep.",
    "sweep_tilt": "Fixed tilt used during sweep mode. Range: 10 to 130 deg. Higher values move the sweep line in one tilt direction. Lower values move it the other way.",
    "sweep_speed": "Sweep travel speed. Range: 1.0 to 30.0 deg/s. Higher values scan faster with less dwell. Lower values scan more slowly and carefully.",
    "waypoint_list": "Ordered list of patrol waypoints. Smart Sentry visits these positions in sequence during waypoint patrol mode.",
    "waypoint_add": "Add the turret's current position to the waypoint list.",
    "waypoint_remove": "Remove the currently selected waypoint from the patrol list.",
    "waypoint_clear": "Clear every saved waypoint from the patrol list.",
    "waypoint_dwell": "Pause time at each waypoint. Range: 0.5 to 30.0 s. Higher values make patrol pauses longer. Lower values keep patrol moving.",
    "waypoint_speed": "Travel speed between waypoints. Range: 1.0 to 30.0 deg/s. Higher values move faster between points. Lower values move more smoothly.",
    "random_pan_min": "Minimum random pan angle. Range: 5 to 185 deg. Increasing it shifts the left/random boundary right.",
    "random_pan_max": "Maximum random pan angle. Range: 5 to 185 deg. Increasing it expands random scan farther right.",
    "random_tilt_min": "Minimum random tilt angle. Range: 10 to 130 deg. Increasing it raises the minimum random tilt bound.",
    "random_tilt_max": "Maximum random tilt angle. Range: 10 to 130 deg. Increasing it expands random scan deeper into the upper bound.",
    "random_dwell": "Pause time at each random position. Range: 0.5 to 30.0 s. Higher values create longer observation pauses. Lower values create more frequent movement.",
    "random_speed": "Travel speed for random scan moves. Range: 1.0 to 30.0 deg/s. Higher values make random scan more active. Lower values make it calmer.",
    "camera_hfov": "Horizontal field of view used for pixel-to-angle conversion. Range: 30 to 180 deg. Higher values assume a wider camera lens and reduce commanded angle per pixel. Lower values assume a narrower lens and increase commanded angle per pixel.",
    "camera_vfov": "Vertical field of view used for pixel-to-angle conversion. Range: 20 to 140 deg. Higher values assume a taller/wider lens view and reduce commanded vertical angle per pixel. Lower values do the opposite.",
    "show_overlay": "Draw Smart Sentry overlay graphics on the video feed. OFF shows a cleaner image. ON shows target and state guidance.",
    "show_scores": "Legacy overlay toggle. The simplified Smart Sentry view shows only one moving target and no multi-target score clutter.",
    "show_zone": "Legacy overlay toggle. The simplified Smart Sentry view hides extra zone outlines by default to keep the screen clean.",
    "manual_step": "Manual movement step size in degrees. Range: 1 to 20 deg. Higher values make each button press move farther. Lower values allow finer manual aiming.",
    "manual_up": "Move the turret up by one manual step.",
    "manual_left": "Move the turret left by one manual step.",
    "manual_home": "Send the turret to its home/guard position.",
    "manual_right": "Move the turret right by one manual step.",
    "manual_down": "Move the turret down by one manual step.",
    "led_toggle": "Toggle the accessory LED output. ON energizes the LED output. OFF disables it.",
    "laser_toggle": "Toggle the accessory laser output. ON energizes the laser output. OFF disables it.",
    "safety_toggle": "Safety lock for manual firing. LOCKED prevents fire output. ARMED allows manual or automatic fire, depending on other settings.",
    "manual_fire": "Manual fire button. Press and hold to fire while safety and trigger mode allow it. Use only when the area is safe.",
    "save_settings": "Save Smart Sentry settings to its dedicated JSON config file so the current setup is restored next time.",
}
