"""SMART SENTRY V3 tooltip definitions.

Keep tooltip copy separate from the UI builder so descriptions stay consistent,
reviewable, and easy to expand as Smart Sentry evolves.
"""

from __future__ import annotations


SENTRY_V2_TOOLTIPS: dict[str, str] = {
    "enable_sentry": "Master enable for Smart Sentry. ON lets the engine scan, track, and engage using its current rules. OFF keeps the module paused and prevents automatic action.",
    "camera_source": "Camera source for Smart Sentry. Leave it blank to default to camera index 0, or enter a camera index like 1 or a stream/URL path to open that source here.",
    "camera_width": "Requested Smart Sentry capture resolution. Choose a standard width x height pair from the dropdown. Higher resolutions increase detail but also CPU/GPU load and USB bandwidth use.",
    "camera_height": "Requested Smart Sentry capture height. In the current UI this is controlled by the standard resolution dropdown rather than a freeform number field.",
    "camera_toggle": "Open or close Smart Sentry's camera source using the configured camera index, URL, or file path.",
    "connection_mode": "Hardware connection topology for Smart Sentry. Choose the wiring mode that matches your setup. For the current Nano migration, select Arduino Nano USB + Debug Board USB when the Nano handles IO/accessories over USB and the Debug Board handles bus-servo motion over its own USB cable. Full WiFi means the PC talks to the ESP32 over UDP only, while the Waveshare single-board bridge drives the Yahboom bus path locally on GPIO18 and GPIO19.",
    "esp32_port": "Primary USB IO board serial COM port. Example: COM20. In USB modes this field may point to either the legacy ESP32 USB IO board or the Arduino Nano USB replacement that handles ASCII IO/control.",
    "scan_esp32_ports": "Scan Windows serial ports and list candidates for the primary USB IO board connection. Use this when the COM port changes or after reconnecting the ESP32 or Nano board.",
    "esp32_port_list": "Detected primary USB IO-board COM ports from the latest scan. Selecting an entry copies that port into the serial IO COM field.",
    "esp32_baud": "Primary USB IO board serial baud rate. Range: 9600 to 921600. Use 115200 for the current ESP32 and Nano serial IO firmware unless you intentionally changed the firmware baud rate.",
    "debug_port": "Debug Board serial COM port. Example: COM19. This is the USB link used for bus-servo pan/tilt control when a debug board is part of the setup.",
    "scan_debug_ports": "Scan Windows serial ports and list candidates for the Debug Board USB connection. Use this after reconnecting the board or if Windows changed the COM number.",
    "debug_port_list": "Detected Debug Board COM ports from the latest scan. Selecting an entry copies that port into the Debug Board COM field.",
    "debug_baud": "Debug Board serial baud rate. Range: 9600 to 921600. Higher values can improve response time if supported. Lower values are slower but may be easier to keep stable on noisy links.",
    "pan_servo_id": "Bus-servo ID for the pan axis. Range: 0 to 253. Changing this must match the servo's programmed ID or Smart Sentry will move the wrong servo or none at all.",
    "tilt_servo_id": "Bus-servo ID for the tilt axis. Range: 0 to 253. Changing this must match the tilt servo's programmed ID.",
    "servo_move_time": "Requested bus-servo move time per command. Range: 0 to 1000 ms. Higher values make movement smoother and slower. Lower values make movement faster and more abrupt.",
    "preset_servo_smooth": "Smooth move-time preset. Uses a higher bus-servo move time so turret motion is slower, calmer, and easier to observe. Best for careful tuning and indoor precision tests.",
    "preset_servo_balanced": "Balanced move-time preset. Keeps bus-servo timing in the middle so the turret is responsive without becoming overly abrupt. This is the default reference timing.",
    "preset_servo_fast": "Fast move-time preset. Uses a lower bus-servo move time so the turret snaps harder and reacts faster, but overshoot risk is higher if the rest of the tuning is aggressive.",
    "udp_host": "ESP32 WiFi host or IP address for UDP control. Example: 192.168.4.1. In full WiFi mode this is the primary runtime control path.",
    "udp_port": "UDP port used for ESP32 WiFi control. Range: 1 to 65535. This must match the port configured in ESP32 firmware.",
    "wifi_pinout": "Show the current Waveshare V3 single-board bridge pin map used by full WiFi mode, including the Yahboom bus UART on GPIO18/GPIO19 and the currently assigned bridge-owned outputs.",
    "invert_pan": "Reverse the pan direction. Enable this if moving right in software makes the turret move left in real hardware.",
    "invert_tilt": "Reverse the tilt direction. Enable this if moving up in software makes the turret move down in real hardware.",
    "connect_toggle": "Open or close the currently configured communication links. In full WiFi mode, Connect opens only the ESP32 UDP link; no runtime USB ports are required.",
    "detection_mode": "Detection algorithm used to find targets. For a simple moving-object workflow, use Motion-Locked Filtered Target so motion is mandatory and size, color, and class only refine moving objects.",
    "preset_detection_frame_diff": "Frame Difference preset. Uses simple frame-to-frame motion detection with tighter contour limits to make moving blobs stand out. Good for testing raw motion response without background learning or AI classification.",
    "preset_detection_backsub": "Background Subtraction preset. Learns a background model and highlights foreground changes. This makes it steadier than frame difference when the camera is stable, but slower to adapt when the scene changes heavily.",
    "preset_detection_yolo": "YOLO Precision preset. Uses only YOLO object detection with higher confidence and area thresholds so the behavior is clearly object-ID driven rather than motion driven.",
    "preset_detection_dual_motion": "Dual Motion preset. Combines frame difference and background subtraction so motion must survive two simple detectors. This is stricter than either motion mode alone.",
    "preset_detection_motion_yolo": "Motion-Gated YOLO preset. Uses motion to decide when YOLO should matter, making it visibly more selective than full-time YOLO modes.",
    "preset_detection_best_hybrid": "Best Hybrid YOLO preset. Background subtraction feeds a more permissive YOLO stage, making this a balanced hybrid that still prefers likely object detections.",
    "preset_detection_color": "Color Watch preset. Uses pure color-mask detection for clearly colored targets. Tune the color preset to your target color for best stability.",
    "preset_detection_color_motion": "Color plus Motion preset. Requires color-mask and frame-difference motion, making it stricter than pure color or pure motion alone.",
    "preset_detection_color_backsub": "Color plus Background preset. Uses color-mask with background subtraction, favoring colored foreground targets over scene noise.",
    "preset_detection_color_yolo": "Color plus YOLO preset. Uses color-mask with YOLO so the system favors colored targets that also look like known classes.",
    "preset_detection_motion_locked": "Motion-Locked Filtered preset. Motion is mandatory and color or YOLO only refine the moving object. This is the most sentry-specific mode for stable single-target tracking.",
    "preset_detection_observer_motion_watch": "Observer Motion Watch preset. Uses permissive background-motion detection so tiny and distant movers still show up even when YOLO cannot classify them.",
    "preset_detection_dog_follow": "Dog Follow preset. Motion-locked tracking tuned for medium/large moving dogs with stable center-follow behavior and lower YOLO area thresholds.",
    "preset_detection_cat_follow": "Cat Follow preset. Motion-locked tracking tuned for smaller agile cats with tighter small-target sensitivity and fast reacquire.",
    "preset_detection_rat_like_follow": "Rat-Like Small Follow preset. Tiny fast-mover tracking profile that uses permissive small-area gating and motion lock for center-follow behavior.",
    "min_contour_area": "Minimum contour area in pixels. Range: 0 to 5,000,000 px. Increase it to ignore small noise and flicker. Decrease it to detect smaller motion blobs.",
    "max_contour_area": "Maximum contour area in pixels. Range: 0 to 5,000,000 px. Increase it to allow larger moving shapes. Decrease it to reject oversized blobs such as whole-scene changes.",
    "yolo_model": "YOLO model file used for object detection. Smaller models are usually faster with lower accuracy. Larger models are usually slower with better recognition quality.",
    "load_yolo_model": "Load the currently selected YOLO model into memory. After a model loads successfully, Smart Sentry remembers that selection and auto-loads it on later startups.",
    "yolo_classes": "Comma-separated YOLO class names Smart Sentry should pay attention to. Example: person,car,dog. Adding more classes increases what can be detected. Narrowing the list reduces distractions.",
    "yolo_confidence": "Minimum YOLO confidence score. Range: 0.05 to 1.00. Increase it to keep only more certain detections. Decrease it to detect weaker or smaller targets, with more false positives.",
    "yolo_min_area": "Minimum YOLO box area in pixels. Range: 0 to 10,000,000 px. Increase it to ignore tiny distant detections. Decrease it to allow smaller targets.",
    "color_preset": "HSV color preset used to refine moving-object detection. Choose Any to ignore color. Choose a preset to keep only moving targets that match that color.",
    "color_min_area": "Minimum color-blob area in pixels. Range: 1 to 5,000,000 px. Increase it to ignore small color noise. Decrease it to detect smaller colored targets.",
    "color_max_area": "Maximum color-blob area in pixels. Range: 1 to 5,000,000 px. Increase it to allow larger colored regions. Decrease it to reject oversized colored areas such as backgrounds.",
    "fusion_strategy": "How color and another detector are combined in hybrid color modes. AND is stricter and reduces false positives. OR is looser and finds more candidates.",
    "fusion_overlap": "Required overlap between detectors in percent. Range: 0 to 100%. Increase it to demand stronger agreement between detectors. Decrease it to allow looser matching.",
    "motion_gate_threshold": "Motion gate threshold used before YOLO in hybrid motion+YOLO modes. Range: 0.1 to 50.0%. Increase it to require stronger motion before YOLO runs. Decrease it to allow more frames through the gate.",
    "motion_ignore_after_move_s": "Ignore motion detections briefly after a turret move so camera self-motion does not look like a target. Lower values reacquire faster after guarding or tracking moves. Higher values are calmer but can delay valid motion targets.",
    "allowed_classes": "List of classes allowed to validate a moving target. Leave the list empty to accept any moving object. Select one or more classes to require a moving object to match those YOLO classes.",
    "preset_filter_wide_net": "Wide Net preset. Accepts any class with lower confidence and very small targets allowed. Use it when you want the sentry to react to as much as possible.",
    "preset_filter_observer_all_movers": "Observer All Movers preset. Accepts any moving object, disables class and shape restrictions, and removes the size ceiling so tiny, far, and large movers can all stay visible.",
    "preset_filter_human_focus": "Human Focus preset. Restricts tracking to people and uses stricter confidence and size limits so non-human detections are filtered out more aggressively.",
    "preset_filter_vehicle_watch": "Vehicle Watch preset. Focuses on vehicle-related classes and ignores smaller detections more strongly. Use it when you want large moving machines to dominate.",
    "preset_filter_small_movers": "Small Movers preset. Keeps smaller targets in play with permissive confidence and a low minimum size, useful when testing pets, small motion, or distant targets.",
    "preset_filter_large_close": "Large Close preset. Requires larger, more confident targets so only obvious near or dominant detections survive the filter.",
    "preset_filter_dog_focus": "Dog Focus preset. Restricts allowed classes to dog with confidence and size limits tuned for moving dogs.",
    "preset_filter_cat_focus": "Cat Focus preset. Restricts allowed classes to cat with tighter small-object size limits for agile pet tracking.",
    "preset_filter_rat_like_motion": "Rat-Like Motion preset. Uses rat class lock (from ratdogcat.pt) with tiny-target size constraints for fast small-animal tracking.",
    "select_all_classes": "Select every YOLO class in the allowed list. This is the widest possible target filter.",
    "select_no_classes": "Clear the allowed class list. With no classes selected, YOLO-qualified targets will normally be filtered out.",
    "min_confidence": "Minimum confidence after class filtering. Range: 0.10 to 0.99. Increase it to accept only stronger detections. Decrease it to keep weaker detections.",
    "min_size": "Minimum target size as a percent of the frame. Range: 0.00 to 50.00%. Increase it to ignore smaller targets. Decrease it to allow smaller targets.",
    "max_size": "Maximum target size as a percent of the frame. Range: 0.00 to 100.00%, where 0 disables the limit. Increase it to allow larger targets. Decrease it to reject very large close-range boxes.",
    "weight_proximity": "Threat weight for closeness to image center. Range: 0.00 to 1.00. Higher values make center-biased targets rank higher. Lower values reduce the importance of center position.",
    "weight_size": "Threat weight for target size. Range: 0.00 to 1.00. Higher values prioritize larger targets. Lower values reduce size influence.",
    "weight_confidence": "Threat weight for detector confidence. Range: 0.00 to 1.00. Higher values favor more certain detections. Lower values make certainty matter less.",
    "weight_class_priority": "Threat weight for configured class priority. Range: 0.00 to 1.00. Higher values make preferred classes dominate ranking more strongly.",
    "weight_speed": "Threat weight for movement speed. Range: 0.00 to 1.00. Higher values prioritize faster-moving targets. Lower values reduce motion urgency.",
    "weight_persistence": "Threat weight for time spent in frame. Range: 0.00 to 1.00. Higher values favor persistent targets. Lower values make dwell time matter less.",
    "weight_approach": "Threat weight for movement toward center/guard focus. Range: 0.00 to 1.00. Higher values prioritize approaching targets. Lower values reduce approach bias.",
    "ml_refinement": "Enable optional machine-learning refinement on top of the hand-tuned threat score. Use only when the required model and sklearn dependency are available.",
    "preset_threat_balanced_guard": "Balanced Guard preset. Keeps center position, preferred class, and basic motion all relevant without letting any single factor dominate. Use this as the neutral reference profile when comparing the other Threat AI presets.",
    "preset_threat_crosshair_snap": "Crosshair Snap preset. Strongly favors targets already near the camera center and moving into the crosshair. This makes Smart Sentry stick to center-biased candidates much more aggressively than the other Threat AI profiles.",
    "preset_threat_speed_hunter": "Speed Hunter preset. Gives much more weight to motion speed and persistence, so fast-moving targets rise above slower objects even if they are not yet centered.",
    "preset_threat_big_target_bias": "Big Target Bias preset. Prioritizes larger detections and more confident boxes. Use this when you want obvious close or large targets to beat smaller moving ones.",
    "preset_threat_class_first": "Class First preset. Makes configured class priority and detector confidence dominate ranking much more strongly than speed, size, or proximity. This is useful when allowed classes matter more than raw motion.",
    "preset_threat_pet_center_lock": "Pet Center Lock preset. Prioritizes center proximity and class relevance so dog/cat targets stay centered and stable during follow.",
    "preset_threat_small_target_follow": "Small Target Follow preset. Boosts center-lock, speed, and persistence so tiny fast movers stay tracked through quick directional changes.",
    "auto_trigger": "Allow Smart Sentry to fire automatically when engagement conditions are met. OFF keeps aiming and tracking active but requires manual fire.",
    "trigger_mode": "Trigger hardware type. Water/MOSFET shows the water-mode pulse settings. Projectile/BB Servo shows the trigger-servo travel settings. Choose the mode that matches the real firing mechanism. Water pulse settings are implemented on the Nano USB IO path and may depend on the active WiFi bridge firmware in ESP32 modes.",
    "trigger_mosfet_pulse_ms": "Water/MOSFET ON time for each fire pulse. Higher values keep the MOSFET output active longer during each pulse. Supported on the Nano USB IO firmware path.",
    "trigger_mosfet_cycle_count": "Number of ON pulses fired for one water-mode fire request. Use 1 for a single pulse or increase it for a short internal pulse train. Supported on the Nano USB IO firmware path.",
    "trigger_mosfet_cycle_off_ms": "OFF gap between water-mode MOSFET pulses inside one fire request. Increase it if the mechanism needs more recovery time between pulses. Supported on the Nano USB IO firmware path.",
    "trigger_servo_rest_deg": "Projectile trigger-servo rest angle sent to the ESP32 at runtime. Increase it only if the trigger linkage needs a different idle position.",
    "trigger_servo_fire_deg": "Projectile trigger-servo fire angle sent to the ESP32 at runtime. Higher values increase trigger travel.",
    "trigger_servo_speed_dps": "Projectile trigger-servo movement rate in degrees per second. Higher values snap the trigger faster. Lower values move it more gently.",
    "preset_engage_demo_track": "Demo Track Only preset. Never fires automatically. It moves slowly, settles longer, and uses tight aim-lock rules so centering behavior is easy to watch on screen.",
    "preset_engage_demo_track_multi": "Demo Track Observer x5 preset. Never fires automatically, keeps motion slow, and allows up to five visible candidates so tiny or distant movers can be observed on screen.",
    "preset_engage_indoor_precision": "Indoor Precision preset. Conservative and exact. It engages only stronger threats, uses slower servo speed, smaller correction steps, and stricter lock tolerances for close indoor testing.",
    "preset_engage_balanced_response": "Balanced Response preset. Default middle-ground profile. It auto-engages at a moderate speed with controlled burst size and moderate lock requirements.",
    "preset_engage_outdoor_chase": "Outdoor Chase preset. Faster and less strict. It reacts sooner, tolerates more aim error, and uses larger correction steps to stay responsive against moving targets over a wider scene.",
    "preset_engage_saturation_burst": "Saturation Burst preset. Most aggressive firing profile. It uses short cooldowns and longer bursts so the behavioral difference is obvious, but it is also the least restrained option.",
    "preset_engage_dog_follow_center": "Dog Follow Center preset. Tracking-first engagement profile for dogs with tight center hold, continuous follow, and auto-trigger disabled.",
    "preset_engage_cat_follow_center": "Cat Follow Center preset. Agile-target follow profile with faster corrections and stricter center lock tuned for cats.",
    "preset_engage_rat_follow_center": "Rat-Like Follow Center preset. Very small fast-target follow profile with highest correction speed and strict center-lock tolerances.",
    "preset_detection_person_yolo": "Person YOLO preset. YOLO inference runs every frame so stationary and slowly moving people are tracked without needing any motion trigger. A lower confidence gate (0.44) keeps partially occluded or distant adults in play; the area floor removes sub-person-sized false positives.",
    "preset_filter_person_focus_closest": "Person Closest First preset. Person-class lock with no upper size ceiling so the nearest adult filling most of the frame is still kept. A single confirmed frame is enough for fast-walking responsiveness. Confidence gate accepts partially visible subjects.",
    "preset_threat_person_closest_center": "Person Closest + Center threat preset. Size is the primary weight so the nearest person (largest box) wins priority. Center bias and walking-speed weight keep the turret continuously aimed during natural movement. Class priority is intentionally lean because the filter already enforces person-only.",
    "preset_engage_person_track_fire": "Person Track + Fire engagement preset. Servo speed and correction step are tuned for a walking adult. Aim-lock tolerances are wider than pet presets so body sway does not break lock. Extended 3 s loss timeout maintains tracking through door frames and brief occlusions.",
    "preset_master_person_track_fire": "Person Track + Fire master profile. Applies Person YOLO detection (no motion gate, catches stationary people), Person Closest First filtering (no size ceiling), Person Closest + Center threat scoring, and person-scale engagement tolerances. The nearest person in frame always wins priority.",
    "preset_master_demo_observer": "Demo Observer master profile. Applies a wide-net observer stack for tiny and distant movers: Observer Motion Watch detection, Observer All Movers filtering, Small Target Follow threat ranking, Demo Track Observer x5 engagement, and Smooth bus-servo timing.",
    "preset_master_indoor_precision": "Indoor Precision master profile. Applies a cautious and exact stack for controlled indoor work: YOLO Precision detection, Human Focus filtering, Class First threat ranking, Indoor Precision engagement, and Smooth bus-servo timing.",
    "preset_master_balanced_sentry": "Balanced Sentry master profile. Applies a general-purpose stack for normal sentry operation: Motion-Locked Filtered detection, Wide Net filtering, Balanced Guard threat ranking, Balanced Response engagement, and Balanced bus-servo timing.",
    "preset_master_vehicle_intercept": "Vehicle Intercept master profile. Applies a faster stack for larger moving machines: Motion-Gated YOLO detection, Vehicle Watch filtering, Speed Hunter threat ranking, Outdoor Chase engagement, and Balanced-to-fast bus-servo timing.",
    "preset_master_aggressive_pursuit": "Aggressive Pursuit master profile. Applies the most forceful coordinated stack: Best Hybrid YOLO detection, Wide Net filtering, Speed Hunter threat ranking, Saturation Burst engagement, and Fast bus-servo timing.",
    "preset_master_dog_tracker": "Dog Tracker master profile. Applies Dog Follow detection, Dog Focus filter, Pet Center Lock threat ranking, and Dog Follow Center engagement for consistent center tracking.",
    "preset_master_cat_tracker": "Cat Tracker master profile. Applies Cat Follow detection, Cat Focus filter, Pet Center Lock threat ranking, and Cat Follow Center engagement for agile center tracking.",
    "preset_master_rat_like_tracker": "Rat-Like Tracker master profile. Applies Rat-Like Follow detection, Rat-Like Motion filter, Small Target Follow threat ranking, and Rat-Like Follow Center engagement for tiny fast movers.",
    "min_threat": "Minimum threat score required before Smart Sentry can engage a target. Range: 0.05 to 0.95. Increase it to be more selective. Decrease it to engage more readily.",
    "burst_shots": "Number of shots in each burst. Range: 1 to 10. Higher values fire longer bursts. Lower values reduce ammo or water use.",
    "burst_interval": "Delay between burst shots in milliseconds. Range: 20 to 500 ms. Higher values slow the burst. Lower values make bursts faster and more aggressive.",
    "inter_target_cooldown": "Cooldown after engaging one target before moving to the next. Range: 0.1 to 5.0 s. Higher values make the system calmer and less jumpy. Lower values speed up retargeting.",
    "cycle_cooldown": "Cooldown after a full engagement cycle. Range: 0.5 to 30.0 s. Higher values slow repeated engagement loops. Lower values keep the system more active.",
    "max_targets_per_cycle": "Maximum number of targets processed per cycle. Range: 1 to 10. Freely adjustable in all modes (single-target mode still enforces 1-target engagement via internal gating). Higher values allow queuing multiple targets; lower values keep cycles shorter.",
    "optimize_travel": "Reorder engagements to reduce servo travel between targets. ON usually improves overall efficiency. OFF keeps a simpler queue order.",
    "engagement_speed": "Servo speed used during engagement. Range: 10 to 100. Higher values make snap-aim faster and more aggressive. Lower values make tracking smoother but slower.",
    "precision_enable": "Enable a precision refinement phase for small or distant targets before firing. ON improves fine aim but can add delay. OFF keeps engagement faster but less precise.",
    "precision_settle": "Time allowed for precision refinement before firing. Range: 0.1 to 3.0 s. Higher values allow more correction time. Lower values fire sooner.",
    "precision_step": "Maximum correction step per precision update in degrees. Range: 0.1 to 5.0 deg. Higher values correct faster but can overshoot. Lower values are smoother but slower.",
    "precision_deadzone_pan": "Pan deadzone used by precision correction. Range: 0.00 to 3.00 deg. Increase to reduce micro-jitter and settle sooner. Decrease to keep correcting until pan is tighter to center.",
    "precision_deadzone_tilt": "Tilt deadzone used by precision correction. Range: 0.00 to 3.00 deg. Increase to reduce vertical twitch and settle sooner. Decrease to hold a tighter vertical center.",
    "precision_error_ema": "EMA smoothing factor for precision error. Range: 0.00 to 1.00. Increase to react faster to the latest frame (more responsive, can be noisier). Decrease to smooth more (steadier, can lag fast targets).",
    "aim_lock_pan_tolerance": "Pan tolerance required for aim-lock state. Range: 0.10 to 5.00 deg. Increase to lock sooner with looser centering. Decrease to require tighter centering before lock.",
    "aim_lock_tilt_tolerance": "Tilt tolerance required for aim-lock state. Range: 0.10 to 5.00 deg. Increase to lock sooner. Decrease to require tighter vertical centering.",
    "aim_lock_required_frames": "Consecutive locked frames before lock is considered stable. Range: 1 to 20 frames. Increase for safer, steadier lock confirmation. Decrease for faster lock response.",
    "fire_trigger_enter_pan": "Pan threshold to enter fire gate. Range: 0.05 to 5.00 deg. Increase to open fire gate earlier. Decrease to wait for tighter pan alignment before gate entry.",
    "fire_trigger_enter_tilt": "Tilt threshold to enter fire gate. Range: 0.05 to 5.00 deg. Increase to open gate sooner. Decrease to require tighter vertical alignment before entry.",
    "fire_trigger_exit_pan": "Pan threshold to remain in fire gate after it is active. Range: 0.05 to 5.00 deg. Increase to prevent gate chatter and stay firing through mild drift. Decrease to drop out sooner and re-correct.",
    "fire_trigger_exit_tilt": "Tilt threshold to remain in fire gate after it is active. Range: 0.05 to 5.00 deg. Increase to stay in fire phase through more vertical drift. Decrease to re-enter correction sooner.",
    "fire_recenter_pan": "Pan drift limit during fire phase before forcing recenter. Range: 0.10 to 5.00 deg. Increase to allow longer bursts with looser tracking. Decrease for tighter centering with more frequent correction breaks.",
    "fire_recenter_tilt": "Tilt drift limit during fire phase before forcing recenter. Range: 0.10 to 5.00 deg. Increase to tolerate more vertical drift while firing. Decrease to keep vertical aim tighter.",
    "target_loss_timeout": "How long to keep trying to recover a target after visual detection drops out. Range: 0.10 to 10.00 s. This is for LOST targets only. It does not limit how long a still-visible stationary target is tracked.",
    "stationary_release_hold_s": "Maximum continuous hold time on one stationary visible target before temporary release protocol can trigger. Range: 1.0 to 60.0 s. After this hold time AND enough repeated fire cycles, Smart Sentry suppresses that same track briefly so PIR/acoustic guard scans can run.",
    "continuous_hunt_on_loss": "When enabled, Smart Sentry stays in hunt mode after target-loss timeout instead of returning to guard immediately. Useful for reacquiring temporarily hidden targets.",
    "adaptive_loss_recovery_enabled": "Enable the adaptive after-loss protocol selector. ON lets Smart Sentry choose between quick handoff and persistent reacquire based on whether other targets are visible. OFF uses the simpler bounded pursuit and local search path.",
    "loss_search_style": "Shared hunting profile for target-loss and PIR no-detect behavior. Hunting keeps the turret close to the last known area first and feels more deliberate. Fast Reacquire reduces dwell and widens early coverage for quicker catch-up.",
    "loss_search_rounds": "Shared pass count for both target-loss and PIR hunt routines. A value of 1 performs one smooth hunt pass through the configured search area. Higher values repeat the hunt with a slightly wider follow-up pass.",
    "loss_handoff_pursuit_time_s": "How long the rapid-handoff protocol continues into the lost target's last motion direction before backing off into a wider search. Lower values hand off sooner. Higher values spend more time chasing the last heading.",
    "loss_handoff_backoff_pan_deg": "Pan step used when the rapid-handoff search backs away from the last seen line. Larger values widen the handoff search faster. Smaller values keep the handoff tighter to the original track.",
    "loss_handoff_tilt_step_deg": "Tilt step used by the rapid-handoff search when it widens around the last seen line. Higher values explore vertically faster. Lower values keep the handoff flatter and steadier.",
    "loss_persistent_retry_passes_sparse": "Maximum bounded retry passes for persistent reacquire in sparse scenes. Higher values spend longer hunting when the scene is otherwise empty.",
    "loss_persistent_retry_passes_crowded": "Maximum bounded retry passes for persistent reacquire in crowded scenes. Keep this lower than sparse-scene retries if you want faster handoff in busier environments.",
    "loss_switch_score_margin": "Threat-score margin another visible target must clear before adaptive loss recovery switches away from the lost target. Higher values make Smart Sentry stay loyal longer. Lower values allow faster handoff.",
    "loss_scene_crowding_threshold": "Visible-target count that separates sparse from crowded scenes for adaptive loss recovery. Lower values make the crowded-scene rules activate sooner.",
    "loss_personality_intensity": "How strongly the adaptive loss search injects personality variation into point ordering. Higher values make the search feel less mechanical. Lower values keep it more literal and repeatable.",
    "loss_personality_velocity_bias": "How much the lost target's last measured heading influences adaptive search ordering. Higher values bias the hunt harder into the last motion direction.",
    "preset_aim_gate_stable_lock": "Stable Lock preset for Advanced Aim Lock and Fire Gate. Tight lock thresholds with higher required lock frames for safer, steadier gating.",
    "preset_aim_gate_balanced_lock": "Balanced Lock preset for Advanced Aim Lock and Fire Gate. Middle-ground tolerances for reliable lock without excessive delay.",
    "preset_aim_gate_fast_lock": "Fast Lock preset for Advanced Aim Lock and Fire Gate. Looser thresholds and fewer lock frames for fastest response on fast movers.",
    "aim_gate_preset_combo": "Choose an Advanced Aim Lock and Fire Gate preset, then apply it to load the grouped lock, gate, and tolerance values without squeezing multiple long preset buttons into one row.",
    "center_fire_radius": "Single center-fire radius control that maps one strict center zone into the related fire-enter, fire-exit, recenter, and aim-lock tolerances.",
    "center_fire_radius_profile": "Choose a sniper center-radius preset and load it into the center-fire radius control. This keeps the preset selection compact while preserving the same small, medium, and large profile behavior.",
    "guard_mode": "Idle/guard behavior when no target is engaged. Static holds one position. Sweep scans left to right. Waypoint follows saved points. Random scans within configured limits.",
    "guard_pan": "Pan angle used as the base guard position. Range: 0 to 270 deg. Higher values look farther right. Lower values look farther left.",
    "guard_tilt": "Tilt angle used as the base guard position. Range: 0 to 110 deg. Higher values move farther toward the upper tilt bound. Lower values move toward the lower bound.",
    "rest_pan": "Pan angle used by Go To Rest and startup/close rest workflows. This is separate from the guard/home pan so the turret can park in a calmer storage pose.",
    "rest_tilt": "Tilt angle used by Go To Rest and startup/close rest workflows. This can differ from the guard/home tilt when you want a safer parked pose.",
    "rest_on_startup_enabled": "When enabled, Smart Sentry can move into the configured rest pose after startup rather than staying at guard/home immediately.",
    "rest_on_close_enabled": "When enabled, Smart Sentry moves into the configured rest pose when the app closes instead of stopping wherever it currently is.",
    "home_move_speed_dps": "Guided move speed used when returning to the configured guard/home position. Higher values make home return more assertive. Lower values make it calmer.",
    "rest_move_speed_dps": "Guided move speed used when entering the rest position. Higher values reach rest faster. Lower values make the park move more deliberate.",
    "pan_limit_min": "Minimum allowed pan angle. Lower values expand left travel. Higher values restrict left travel and keep the turret inside safer mechanical limits.",
    "pan_limit_max": "Maximum allowed pan angle. Higher values expand right travel. Lower values restrict right travel and protect the mechanism.",
    "tilt_limit_min": "Minimum allowed tilt angle. Lower values allow more travel toward the lower bound. Higher values restrict that direction to avoid collisions or stall zones.",
    "tilt_limit_max": "Maximum allowed tilt angle. Higher values allow more travel toward the upper bound. Lower values reduce vertical reach and can protect hardware.",
    "go_guard": "Command the turret to move immediately to the configured guard position.",
    "go_rest": "Command the turret to move immediately to the configured rest position.",
    "set_current_guard": "Use the turret's current position as the new guard position. Helpful after manually aiming to the exact resting angle you want.",
    "set_current_rest": "Use the turret's current position as the new saved rest position.",
    "sweep_min": "Minimum pan limit for sweep mode. Range: 0 to 270 deg. Increasing it shifts the sweep window right. Decreasing it shifts the left edge farther left.",
    "sweep_max": "Maximum pan limit for sweep mode. Range: 0 to 270 deg. Increasing it extends the sweep farther right. Decreasing it narrows the sweep.",
    "sweep_tilt": "Fixed tilt used during sweep mode. Range: 0 to 110 deg. Higher values move the sweep line deeper into the upper tilt bound. Lower values move it toward the lower bound.",
    "sweep_speed": "Sweep travel speed. Range: 1.0 to 30.0 deg/s. Higher values scan faster with less dwell. Lower values scan more slowly and carefully.",
    "waypoint_list": "Ordered list of patrol waypoints. Smart Sentry visits these positions in sequence during waypoint patrol mode.",
    "waypoint_add": "Add the turret's current position to the waypoint list.",
    "waypoint_remove": "Remove the currently selected waypoint from the patrol list.",
    "waypoint_clear": "Clear every saved waypoint from the patrol list.",
    "waypoint_dwell": "Pause time at each waypoint. Range: 0.5 to 30.0 s. Higher values make patrol pauses longer. Lower values keep patrol moving.",
    "waypoint_speed": "Travel speed between waypoints. Range: 1.0 to 30.0 deg/s. Higher values move faster between points. Lower values move more smoothly.",
    "random_pan_min": "Minimum random pan angle. Range: 0 to 270 deg. Increasing it shifts the left/random boundary right.",
    "random_pan_max": "Maximum random pan angle. Range: 0 to 270 deg. Increasing it expands random scan farther right.",
    "random_tilt_min": "Minimum random tilt angle. Range: 0 to 110 deg. Increasing it raises the minimum random tilt bound.",
    "random_tilt_max": "Maximum random tilt angle. Range: 0 to 110 deg. Increasing it expands random scan deeper into the upper bound.",
    "random_dwell": "Pause time at each random position. Range: 0.5 to 30.0 s. Higher values create longer observation pauses. Lower values create more frequent movement.",
    "random_speed": "Travel speed for random scan moves. Range: 1.0 to 30.0 deg/s. Higher values make random scan more active. Lower values make it calmer.",
    "camera_hfov": "Horizontal field of view used for pixel-to-angle conversion. Range: 30 to 180 deg. Higher values assume a wider camera lens and reduce commanded angle per pixel. Lower values assume a narrower lens and increase commanded angle per pixel.",
    "camera_vfov": "Vertical field of view used for pixel-to-angle conversion. Range: 20 to 140 deg. Higher values assume a taller/wider lens view and reduce commanded vertical angle per pixel. Lower values do the opposite.",
    "show_overlay": "Draw Smart Sentry overlay graphics on the video feed. OFF shows a cleaner image. ON shows target and state guidance.",
    "show_scores": "Legacy overlay toggle. The simplified Smart Sentry view shows only one moving target and no multi-target score clutter.",
    "show_zone": "Legacy overlay toggle. The simplified Smart Sentry view hides extra zone outlines by default to keep the screen clean.",
    "manual_step": "Manual movement step size in degrees. Range: 1 to 20 deg. Higher values make each button press move farther. Lower values allow finer manual aiming.",
    "manual_top_left": "Jump to the top-left manual corner using the configured minimum pan and maximum tilt limits.",
    "manual_up_left": "Move the turret one manual step up and left at the same time.",
    "manual_max_tilt": "Jump directly to the configured maximum tilt limit while keeping the current pan angle. Uses the same angle clamp path as other absolute manual moves.",
    "manual_up": "Move the turret up by one manual step.",
    "manual_up_right": "Move the turret one manual step up and right at the same time.",
    "manual_top_right": "Jump to the top-right manual corner using the configured maximum pan and maximum tilt limits.",
    "manual_min_pan": "Jump directly to the configured minimum pan limit while keeping the current tilt angle.",
    "manual_left": "Move the turret left by one manual step.",
    "manual_home": "Send the turret to its home/guard position.",
    "manual_right": "Move the turret right by one manual step.",
    "manual_max_pan": "Jump directly to the configured maximum pan limit while keeping the current tilt angle.",
    "manual_bottom_left": "Jump to the bottom-left manual corner using the configured minimum pan and minimum tilt limits.",
    "manual_down_left": "Move the turret one manual step down and left at the same time.",
    "manual_down": "Move the turret down by one manual step.",
    "manual_down_right": "Move the turret one manual step down and right at the same time.",
    "manual_min_tilt": "Jump directly to the configured minimum tilt limit while keeping the current pan angle.",
    "manual_bottom_right": "Jump to the bottom-right manual corner using the configured maximum pan and minimum tilt limits.",
    "led_toggle": "Toggle the accessory LED output. ON energizes the LED output. OFF disables it.",
    "laser_toggle": "Toggle the accessory laser output. ON energizes the laser output. OFF disables it.",
    "acc_toggle": "Toggle the accessory relay (GPIO 25). ON energizes the relay output. OFF disables it. Sends the G token in commands.",
    "spare_toggle": "Toggle the spare relay (GPIO 26). ON energizes the relay output. OFF disables it. Sends the A token in commands.",
    "safety_toggle": "Safety lock for manual firing. LOCKED prevents fire output. ARMED allows manual or automatic fire, depending on other settings.",
    "manual_fire": "Manual fire button. In water mode, pressing it starts one configured MOSFET pulse train using the water trigger settings. In projectile GPIO13 servo mode, pressing it sends one trigger-servo pulse. Use only when the area is safe.",
    "auto_lighting_enabled": "Enable automatic LED brightness control. ON samples scene brightness and drives LED PWM between the configured auto minimum and maximum values. In auto mode the app turns the LED on when the scene is dim and reduces it back to 0 when the scene is bright.",
    "led_pwm_value": "Manual LED PWM level. Range: 0 to 255. Increase it for a brighter fixed LED output when auto lighting is OFF. Decrease it to dim the LED, with 0 fully off.",
    "auto_brightness_threshold": "Scene-darkness threshold for auto lighting. Range: 0 to 255. Scene luma is the average frame brightness where 0 is black and 255 is bright. If scene luma falls below this threshold, auto lighting turns the LED on and increases PWM as the scene gets darker.",
    "auto_pwm_min": "Minimum LED PWM auto lighting may use. Range: 0 to 255. Increase it to keep a brighter floor in dim scenes. Decrease it to let the LED stay dimmer when only a little extra light is needed.",
    "auto_pwm_max": "Maximum LED PWM auto lighting may use. Range: 0 to 255. Increase it to allow brighter output in very dark scenes. Decrease it to cap brightness, glare, and power draw.",
    "sound_enabled": "Master toggle for Smart Sentry procedural sound cues. ON sends short buzzer tones for settings changes, detections, tracking movement, target lock, firing, PIR events, and guard scanning. OFF silences all sound commands.",
    "sound_volume": "Always-visible sound volume control for Smart Sentry buzzer cues. Range: 0 to 100%. Increasing makes buzzer cues louder. Decreasing makes cues quieter; 0% mutes sound without turning the feature off.",
    "human_voice_enabled": "Enable local Qt text-to-speech output for Smart Sentry and the in-app assistant. When ON, Test Voice, fallback phrase checks, and conversational replies can use the selected Windows SAPI voice.",
    "mute_buzzer_when_human_voice_enabled": "Mute the board buzzer path while human voice mode is ON so firmware buzzer cues do not overlap the spoken assistant or spoken identity announcements.",
    "human_voice_style": "Speech style preset for the local human voice. Each preset adjusts rate, pitch, and volume together so you can change the spoken character quickly without tuning each slider manually.",
    "human_voice_name": "Choose which local Kokoro voice Smart Sentry should use for offline speech. This list comes from the installed Kokoro voices bundle, so third-party models will only appear here after they are converted into a compatible local Kokoro asset.",
    "human_voice_test": "Speak the main human voice test phrase using the currently selected Qt voice, style, and volume settings.",
    "human_voice_rate": "Relative speech rate for the local human voice. Lower values speak more slowly; higher values speak faster.",
    "human_voice_pitch": "Relative speech pitch for the local human voice. Lower values sound deeper; higher values sound brighter.",
    "human_voice_volume": "Relative speech volume for the local human voice path inside Qt. Increase it if the voice is too quiet even when Windows output is correct.",
    "human_voice_fallback": "Speak a short fallback phrase through the current Qt voice path. Use this to separate a general speech-routing problem from assistant-specific wording or timing.",
    "human_voice_stop": "Stop the current Qt speech playback and return the local voice engine to a ready state.",
    "human_voice_refresh": "Refresh the Voice Diagnostics panel and log the current backend, selected voice, speech state, and buzzer-mute routing.",
    "human_voice_validate": "Run a short validation pass for the currently selected Qt voice. This confirms that Qt can select that voice and enter a valid speech state, but it does not prove that the PC speakers are audible.",
    "human_voice_validate_all": "Run the same validation pass across every detected Qt voice so you can see which voices Qt can select and start successfully in this runtime.",
    "ai_auto_speak": "Automatically speak assistant replies through the local human voice when auto-speak is ON, human voice is enabled, and the Qt speech backend is available. If any of those are missing, replies stay text-only.",
    "ai_speak_last": "Replay the most recent assistant reply through the current local human voice settings.",
    "ai_request_examples": "Examples of supported local assistant requests, including movement, detection-mode changes, shortcut toggles, face-recognition toggles, and spoken status summaries.",
    "pir_enabled": "Enable/disable all PIR motion sensors. When enabled, PIR hits send the turret to the sensor cue, hold there briefly, then run a local-area hunt if vision still sees nothing.",
    "pir_cue_pan": "Pan angle (0-270°) to aim at when this PIR sensor detects motion. When the sensor fires, the turret slews to this look angle.",
    "pir_cue_tilt": "Tilt angle (0-110°) to aim at when this PIR sensor detects motion. Combined with Pan Cue to form the initial search point.",
    "pir_sensor_enabled": "Enable/disable this specific PIR sensor. Disabled sensors are ignored even when PIR guard is enabled.",
    "pir_scan_pan_range": "Maximum horizontal search span around the PIR cue point if no target is found. The local hunt now starts near the cue first, then widens toward this limit.",
    "pir_scan_tilt_range": "Maximum vertical search span around the PIR cue point if no target is found. Default is 45° so the PIR hunt can work the full nearby zone vertically before giving up.",
    "pir_grid_resolution": "Adaptive scan grid density (2-6). Higher values (5-6) create finer grids with more points to check but take longer. Lower values (2-3) create coarser grids and scan faster.",
    "pir_scan_speed": "Speed (deg/s) for scan grid traversal. Higher values scan the area faster. Lower values search more carefully at each point.",
    "acoustic_sweep_speed_dps": "Acoustic alert secondary sweep speed. Range: 2.0 to 80.0 deg/s. Higher values scan the post-anomaly area faster but with less dwell per angle. Lower values scan more slowly and deliberately, improving observation time per sector.",
    "pir_cue_hold_time": "Short hold time at the exact PIR cue point before the local hunt begins. Lower values make the turret leave the cue faster. Higher values keep it still a little longer before searching. This is the pre-hunt dwell; current builds do not intentionally hold still again after the hunt completes.",
    "pir_confirm_timeout": "Overall confirmation window for the active PIR cue. The visible pause is controlled mainly by Cue Hold, while this timeout bounds how long the cue remains active before the hunt is considered stale.",
    "pir_scan_on_no_detect": "When checked, if the turret reaches a PIR cue point and the camera finds nothing, automatically run a localized hunt that starts near the cue and then widens through the PIR zone. When the hunt finishes without a target, Smart Sentry returns to the configured guard/home position instead of lingering at the last hunt point.",
    "pir_event_blink_enabled": "Blink GPIO2 / the ESP32 status LED when a PIR event is detected. Turn this off if you do not want the board flashing when PIR sensors trip while the app is idle or closed.",
    "pir_layout_120": "Apply the 120-degree three-sector PIR helper layout for sensors spaced roughly evenly around the turret. This fills in cue angles and the recommended broad 45 by 45 degree hunt defaults for that layout.",
    "servo_udp_host": "Secondary ESP32 WiFi host or IP address used only in the dual-ESP32 topology where a second WiFi endpoint owns pan/tilt motion.",
    "servo_udp_port": "UDP port for the secondary ESP32 WiFi endpoint in the dual-ESP32 topology. This must match the secondary board firmware.",
    "preset_filter_car_focus": "Car Focus preset. Restricts filtering toward car-class detections with thresholds tuned for midsize vehicles rather than general motion.",
    "preset_filter_bird_focus": "Bird Focus preset. Keeps smaller elevated targets eligible while staying more selective than the general small-movers profile.",
    "preset_filter_sniper_small_motion": "Sniper Small Motion preset. Small-target motion filter for distant movers where tiny detections must remain valid without fully opening the gate.",
    "preset_filter_sniper_medium_motion": "Sniper Medium Motion preset. Medium-distance motion filter that stays more selective than the wide observer profiles.",
    "preset_filter_sniper_large_motion": "Sniper Large Motion preset. Larger-target long-range motion filter for distant people, pets, or equipment.",
    "preset_filter_sniper_small_rodent": "Sniper Small Rodent preset. Very small target filter stack intended for rodent-scale motion and tiny semantic detections.",
    "preset_filter_sniper_medium_pet": "Sniper Medium Pet preset. Medium pet-sized filter stack with tighter long-range constraints than the everyday cat and dog follow profiles.",
    "preset_filter_sniper_large_person": "Sniper Large Person preset. Person-focused long-range filter that preserves distant adult-sized detections without admitting unrelated clutter.",
    "preset_threat_sniper_small_center_lock": "Sniper Small Center Lock preset. Threat ranking tuned for tiny distant targets where center stability and persistence matter more than raw box size.",
    "preset_threat_sniper_medium_center_lock": "Sniper Medium Center Lock preset. Medium-distance center-lock ranking that balances stability with slightly faster handoff than the smallest-target sniper profile.",
    "preset_threat_sniper_large_center_lock": "Sniper Large Center Lock preset. Long-range ranking for larger targets where center bias stays dominant but confidence and size still help break ties.",
    "preset_engage_color_follow_track": "Color Follow Track preset. Tracking-first engagement profile for color-locked targets where stable follow matters more than aggressive fire cadence.",
    "preset_engage_sniper_small_center": "Sniper Small Center preset. Precision-first engagement profile for tiny distant targets where the turret should settle carefully before committing to fire.",
    "preset_engage_sniper_medium_center": "Sniper Medium Center preset. Balanced precision profile for medium-distance targets with strict center lock but faster recovery than the smallest-target sniper mode.",
    "preset_engage_sniper_large_center": "Sniper Large Center preset. Long-range precision engagement profile for larger targets where the turret can move a bit more assertively without giving up center discipline.",
    "preset_master_color_follow_small": "Color Follow Small master profile. Applies a coordinated color-led stack for smaller targets where color identity is the primary discriminator.",
    "preset_master_sniper_movement_small": "Sniper Movement Small master profile. Combines small-target motion detection, sniper filtering, center-lock threat ranking, and precision engagement for tiny distant movers.",
    "preset_master_sniper_movement_medium": "Sniper Movement Medium master profile. Medium-distance motion sniper stack with a little more responsiveness than the small-target version.",
    "preset_master_sniper_movement_large": "Sniper Movement Large master profile. Larger-target long-range motion stack for distant people, pets, or equipment.",
    "preset_master_sniper_color_small": "Sniper Color Small master profile. Small-target color-guided sniper stack for scenes where color identity matters more than semantic class.",
    "preset_master_sniper_color_medium": "Sniper Color Medium master profile. Medium-distance color-guided sniper stack with balanced strictness and reacquire speed.",
    "preset_master_sniper_color_large": "Sniper Color Large master profile. Larger-target color-guided sniper stack for strong visual identity at distance.",
    "preset_master_sniper_yolo_small": "Sniper YOLO Small master profile. Tiny-target semantic sniper stack that trusts class-driven detections more than pure motion or color.",
    "preset_master_sniper_yolo_medium": "Sniper YOLO Medium master profile. Medium-distance semantic sniper stack with balanced center lock and precision engagement.",
    "preset_master_sniper_yolo_large": "Sniper YOLO Large master profile. Larger-target semantic sniper stack for distant human or vehicle-class follow.",
    "preset_master_sniper_hybrid_small": "Sniper Hybrid Small master profile. Small-target hybrid stack that blends motion, semantic, and center-lock logic for distant movers.",
    "preset_master_sniper_hybrid_medium": "Sniper Hybrid Medium master profile. Medium-distance hybrid sniper stack with a more forgiving target scale than the small variant.",
    "preset_master_sniper_hybrid_large": "Sniper Hybrid Large master profile. Larger-target hybrid sniper stack for long-range scenes where multiple cues should agree before engagement.",
    "show_guard_crosshair": "Show the saved guard or home crosshair overlay even when no target is engaged. Useful while tuning guard position and patrol geometry.",
    "pir_cross_lockout_ms": "Ignore near-simultaneous PIR hits from neighboring sensors for this many milliseconds so one crossing target does not appear as multiple competing cue events.",
    "scope_view_enabled": "Enable the circular scope-style presentation during ENGAGING state. This changes only the display layer, not the detector or fire logic.",
    "scope_radius": "Scope circle radius as a percent of the frame. Larger values show more of the original frame inside the scope; smaller values create a tighter magnified look.",
    "scope_vignette": "Background vignette opacity outside the scope circle. Higher values darken the outside area more strongly and make the scope effect more pronounced.",
    "no_fire_mask_name": "Name for the next no-fire mask polygon captured from the live video. Use descriptive names so blocked sectors remain easy to identify later.",
    "no_fire_mask_capture": "Toggle live capture mode for a new no-fire polygon. Click points on the video to define the blocked region before finishing the mask.",
    "no_fire_mask_finish": "Finish the current no-fire polygon and save it into the active mask list.",
    "no_fire_mask_undo": "Remove the most recent draft vertex from the in-progress no-fire polygon.",
    "no_fire_mask_clear": "Discard the current draft polygon without saving it.",
    "no_fire_mask_toggle": "Enable or disable the selected saved no-fire masks without deleting them.",
    "no_fire_mask_remove": "Delete the selected saved no-fire masks from the current configuration.",
    "show_no_fire_masks": "Draw saved no-fire mask polygons on the video overlay so blocked firing sectors stay visible during tuning.",
    "mask_trace": "Enable extra no-fire mask diagnostics for troubleshooting polygon projection and block decisions.",
    "mask_trace_dump": "Write a one-time snapshot of current no-fire mask diagnostics to the runtime log for inspection.",
    "prompted_enabled": "Enable prompted-target matching alongside the normal detector stack so saved visual exemplars can participate in tracking.",
    "prompted_auto_fire": "Allow prompted-target matches to satisfy auto-fire logic when the rest of the engagement conditions are met.",
    "prompted_append_selected": "Append newly imported examples to the currently selected prompted target instead of always creating a separate target entry.",
    "prompted_name": "Base name used when creating or extending prompted targets from live capture, images, or video.",
    "prompted_live": "Capture a prompted target directly from the live video feed using the current frame as the source.",
    "prompted_image": "Import a prompted target example from a still image file.",
    "prompted_video": "Import prompted target examples from a video clip.",
    "prompted_target_list": "Saved prompted-target profiles. Select an entry to tune its matching thresholds and maintenance actions.",
    "prompted_min_score": "Minimum match score required before a prompted target counts as a valid match.",
    "prompted_confirm_hits": "Number of confirming hits needed before a prompted target is treated as stable rather than transient.",
    "prompted_lost_timeout": "How long to keep a prompted target alive after matches temporarily disappear.",
    "prompted_search_padding": "Extra padding around the last known prompted-target location when searching for the next match.",
    "prompted_global_interval": "How often the matcher should fall back to a broader global search instead of searching only near the previous prompted match.",
    "prompted_rename": "Rename the currently selected prompted-target profile.",
    "prompted_remove_last_example": "Remove the most recently added example from the selected prompted-target profile.",
    "prompted_remove": "Delete the selected prompted-target profile entirely.",
    "custom_master_profile_select": "Choose a saved custom coordinated profile to inspect, edit, or overwrite.",
    "custom_master_use_active": "Copy the currently active coordinated profile into the editor so it can be updated or saved under a new name.",
    "custom_master_new": "Clear the custom coordinated profile editor and start from a new profile name.",
    "custom_master_name": "Name for a custom coordinated master profile that bundles Detection, Filter, Threat AI, Engage, and servo timing choices.",
    "custom_master_update": "Overwrite the selected saved custom coordinated profile with the current live stack.",
    "custom_master_save_as_new": "Save the current coordinated stack as a brand-new custom master profile without overwriting the selected one.",
    "export_runtime_snapshot": "Write one timestamped runtime data export under the repo snapshots folder, including config, engine state, comm telemetry, camera status, YOLO status, file references, recent log lines, and the recorded runtime conversation summary. This export is read-only instrumentation for diagnostics and future AI analysis and does not change live sentry behavior.",
    "export_runtime_conversation": "Write one timestamped full runtime conversation export with operator transcripts, normalized voice commands, assistant replies, spoken confirmations, and analysis hints so the session can be reviewed and improved later.",
    "open_runtime_snapshot_folder": "Open the snapshot export folder that contains the latest runtime data export files.",
    "serial_log_filter_all": "Show every Serial / Transport Output line regardless of category. Use this when you need the full timeline instead of a filtered troubleshooting view.",
    "serial_log_filter_system": "Show general system and connection messages that do not match a more specific category. Useful for startup, connect/disconnect, and general status notes.",
    "serial_log_filter_pir": "Show only PIR-related log lines, including PIR events, cue/search notes, and PIR hunt status.",
    "serial_log_filter_movement": "Show only move-related log lines such as pan/tilt motion, guard/rest/home moves, tracking moves, recovery searches, and servo feedback.",
    "serial_log_filter_camera": "Show only camera and detector log lines, including open/read/recovery messages plus frame, model, and YOLO notes.",
    "serial_log_filter_safety": "Show only safety and fire-path log lines, including safety arming, no-fire-mask blocks, fire warnings, and engagement-block messages.",
    "serial_log_filter_accessory": "Show only accessory-control log lines, including LED, laser, accessory relay, spare relay, and control-source messages.",
    "export_serial_log": "Write one timestamped text export of the current Serial Output panel into the serial-log export folder for later AI analysis or troubleshooting.",
    "open_serial_log_folder": "Open the folder that contains exported Serial Output log files.",
    "save_settings": "Save Smart Sentry settings to its dedicated JSON config file so the current setup is restored next time.",
    "apply_settings": "Apply pending settings changes to the live runtime immediately without waiting for the debounce window or a full settings save.",
}
